# Generated by Django 2.2.17 on 2021-02-07 05:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import judge.models.problem_data
import judge.models.profile
import judge.utils.problem_data


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0113_contest_decimal_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemdata',
            name='checker_file',
            field=models.FileField(blank=True, null=True, storage=judge.utils.problem_data.ProblemDataStorage(), upload_to=judge.models.problem_data.problem_directory_file, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['py'])], verbose_name='checker file'),
        ),
    ]
